apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-seed-app
  labels:
    app: seed-app
spec:
  replicas: {{ .Values.seedApp.replicaCount }}
  selector:
    matchLabels:
      app: seed-app
  template:
    metadata:
      labels:
        app: seed-app
    spec:
      containers:
        - name: seed-app
          image: "{{ .Values.seedApp.image.repository }}:{{ .Values.seedApp.image.tag }}"
          imagePullPolicy: {{ .Values.seedApp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            {{- if eq .Values.backend.name "vllm" }}
            - name: INFERENCE_ENDPOINT
              value: "http://{{ .Values.vllm.service.name }}:{{ .Values.vllm.service.port }}"
            - name: INFERENCE_MODEL
              value: "{{ .Values.vllm.model }}"
            {{- else if eq .Values.backend.name "tgi" }}
            - name: INFERENCE_ENDPOINT
              value: "http://{{ .Values.tgi.service.name }}:{{ .Values.tgi.service.port }}"
            - name: INFERENCE_MODEL
              value: "{{ .Values.tgi.model }}"
            {{- end }}
            - name: INFERENCE_TIMEOUT
              value: "{{ .Values.seedApp.timeout }}"