apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-seed-app
  labels:
    app: seed-app
spec:
  replicas: {{ .Values.seedApp.replicaCount }}
  selector:
    matchLabels:
      app: seed-app
  template:
    metadata:
      labels:
        app: seed-app
    spec:
      containers:
        - name: seed-app
          image: "{{ .Values.seedApp.image.repository }}:{{ .Values.seedApp.image.tag }}"
          imagePullPolicy: {{ .Values.seedApp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: VLLM_ENDPOINT
              value: "{{ .Values.seedApp.env.VLLM_ENDPOINT }}"
            - name: VLLM_MODEL
              value: "{{ .Values.seedApp.env.VLLM_MODEL }}"
            - name: VLLM_TIMEOUT
              value: "{{ .Values.seedApp.env.VLLM_TIMEOUT }}"
