apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-seed-app
  labels:
    app: seed-app
spec:
  replicas: {{ .Values.seedApp.replicaCount }}
  selector:
    matchLabels:
      app: seed-app
  template:
    metadata:
      labels:
        app: seed-app
    spec:
      containers:
        - name: seed-app
          image: "{{ .Values.seedApp.image.repository }}:{{ .Values.seedApp.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.seedApp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP