apiVersion: v1
kind: Service
metadata:
  name: ollama-service # Using a fixed name for simplicity
spec:
  type: ClusterIP
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: api
      protocol: TCP
      name: api