apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-seed-app-service
  # Prometheus'un bu servisi bulması için etiket ekliyoruz
  labels:
    app: seed-app
spec:
  type: {{ .Values.seedApp.service.type }}
  selector:
    app: seed-app
  ports:
    - name: http
      port: {{ .Values.seedApp.service.port }}
      targetPort: http
      protocol: TCP
    # Metrik portunu tanımlıyoruz
    - name: metrics
      port: {{ .Values.seedApp.service.metricsPort }}
      targetPort: http # Metrikler de aynı uygulama portundan yayınlanıyor
      protocol: TCP