apiVersion: v1
kind: Service
metadata:
  name: vllm-server
spec:
  type: ClusterIP
  selector:
    app: vllm
  ports:
    - name: http
      port: {{ .Values.vllm.service.port }}
      targetPort: http
      protocol: TCP
