apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vllm
  labels:
    app: vllm
spec:
  replicas: {{ .Values.vllm.replicaCount }}
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      nodeSelector:
{{ toYaml .Values.vllm.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.vllm.tolerations | indent 8 }}
      containers:
        - name: vllm
          image: "{{ .Values.vllm.image.repository }}:{{ .Values.vllm.image.tag }}"
          imagePullPolicy: {{ .Values.vllm.image.pullPolicy }}
          args:
            - "--model={{ .Values.vllm.model }}"
            {{- if .Values.vllm.quantization }}
            - "--quantization={{ .Values.vllm.quantization }}"
            {{- end }}
            - "--host=0.0.0.0"
            - "--port={{ .Values.vllm.service.port }}"
            - "--gpu-memory-utilization={{ .Values.vllm.gpuMemoryUtilization }}"
            - "--download-dir=/tmp/vllm"
          ports:
            - name: http
              containerPort: {{ .Values.vllm.service.port }}
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
            - name: LD_LIBRARY_PATH
              value: "/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vllm-secrets
                  key: HUGGING_FACE_HUB_TOKEN
          resources:
{{ toYaml .Values.vllm.resources | indent 12 }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.vllm.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            tcpSocket:
              port: {{ .Values.vllm.service.port }}
            initialDelaySeconds: 0
            periodSeconds: 20
            failureThreshold: 10
          startupProbe:
            tcpSocket:
              port: {{ .Values.vllm.service.port }}
            periodSeconds: 10
            failureThreshold: 120
