apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-pipeline
  namespace: argocd

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: 'https://github.com/Battlemon6/llm-pipeline-mvp'
    targetRevision: main
    path: llm-chart
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true