# argocd/application.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-pipeline
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: seed-app=europe-west2-docker.pkg.dev/llm-pipeline-birkbeck/llm-app-images/seed-app

    argocd-image-updater.argoproj.io/seed-app.update-strategy: latest

    argocd-image-updater.argoproj.io/seed-app.helm.image-spec: seedApp.image.tag

    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-updater-creds

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: 'https://github.com/Battlemon6/llm-pipeline-mvp'
    targetRevision: main
    path: llm-chart
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true