apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-pipeline
  namespace: argocd
  annotations:
    # Image Updater hangi imajı izleyecek
    argocd-image-updater.argoproj.io/image-list: |
      seed-app=europe-west2-docker.pkg.dev/llm-pipeline-birkbeck/llm-app-images/seed-app

    # En yeni build'e güncelle
    argocd-image-updater.argoproj.io/seed-app.update-strategy: newest-build

    # Helm değerlerinde repo ve tag alanlarını AYRI AYRI güncelle
    argocd-image-updater.argoproj.io/seed-app.helm.image-name: seedApp.image.repository
    argocd-image-updater.argoproj.io/seed-app.helm.image-tag: seedApp.image.tag

    # Argo CD'ye direkt yaz (git write-back gerekmez)
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: 'https://github.com/Battlemon6/llm-pipeline-mvp'
    targetRevision: main
    path: llm-chart
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
