apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obs-dcgm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: obs
  source:
    repoURL: https://nvidia.github.io/dcgm-exporter/helm-charts
    chart: dcgm-exporter
    targetRevision: 4.5.0
    helm:
      releaseName: obs-dcgm
      valuesObject:
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        serviceMonitor:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
