apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obs-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: obs
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 59.1.0
    helm:
      releaseName: obs-mon
      valuesObject:
        crds:
          enabled: false
        
        prometheusOperator:
          namespaces:
            additional:
            - default

        prometheus:
          prometheusSpec:
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
        prometheus-node-exporter:
          tolerations:
            - operator: Exists
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true