# argocd/monitoring-app.yaml (NİHAİ VE DOĞRU VERSİYON)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 59.1.0
    helm:
      valuesObject:
        crds:
          enabled: false
        alertmanager:
          alertmanagerSpec:
            nodeSelector:
              cloud.google.com/gke-accelerator: null
            storage: {}
        grafana:
          nodeSelector:
            cloud.google.com/gke-accelerator: null
        kube-state-metrics:
          nodeSelector:
            cloud.google.com/gke-accelerator: null
        prometheus:
          prometheusSpec:
            nodeSelector:
              cloud.google.com/gke-accelerator: null
            storageSpec:
              emptyDir: {}
            serviceMonitorNamespaceSelector: {}
        prometheus-node-exporter:
          tolerations:
            - operator: "Exists"
        prometheusOperator:
          nodeSelector:
            cloud.google.com/gke-accelerator: null
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true