seedApp:
  replicaCount: 1
  image:
    repository: europe-west2-docker.pkg.dev/llm-pipeline-birkbeck/llm-app-images/seed-app
    tag: "v3"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
    metricsPort: 8000
  env:
    VLLM_ENDPOINT: "http://vllm-server:8000"
    VLLM_MODEL: "TheBloke/Mistral-7B-Instruct-v0.2-AWQ"
    VLLM_TIMEOUT: "120"

vllm:
  replicaCount: 1
  image:
    repository: vllm/vllm-openai
    tag: "latest"
    pullPolicy: IfNotPresent

  model: "TheBloke/Mistral-7B-Instruct-v0.2-AWQ"
  quantization: "awq"
  gpuMemoryUtilization: 0.8

  persistence:
    enabled: true
    size: 20Gi
    storageClassName: "premium-rwo"

  service:
    port: 8000
    # vLLM'in /metrics endpoint'i bu porttan yayın yapar
    metricsPort: 8000

  nodeSelector:
    cloud.google.com/gke-accelerator: "nvidia-l4"

  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"

  resources:
    requests:
      nvidia.com/gpu: 1
    limits:
      nvidia.com/gpu: 1

# --- YENİ BÖLÜM ---
# kube-prometheus-stack için yapılandırma
prometheus:
  # kube-prometheus-stack'i etkinleştir
  enabled: true

  # Prometheus ve Alertmanager'ı sadece CPU nodlarında çalışacak şekilde yapılandır
  prometheus:
    prometheusSpec:
      nodeSelector:
        cloud.google.com/gke-accelerator: null
  alertmanager:
    alertmanagerSpec:
      nodeSelector:
        cloud.google.com/gke-accelerator: null

  # Grafana'yı sadece CPU nodlarında çalışacak şekilde yapılandır
  grafana:
    nodeSelector:
      cloud.google.com/gke-accelerator: null

  # seed-app ve vllm servislerindeki /metrics endpoint'lerini otomatik olarak bul
  prometheusOperator:
    serviceMonitorSelectorNilUsesHelmValues: false

dcgmExporter:
  # dcgm-exporter'ı etkinleştir
  enabled: true

  # Bu, exporter'ın GPU nodlarındaki "taint"i tolere etmesini sağlar
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"

  # Prometheus'un metrikleri bulabilmesi için ServiceMonitor oluştur
  serviceMonitor:
    enabled: true