name: Build, Push, and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: llm-pipeline-birkbeck
  GAR_LOCATION: europe-west2
  IMAGE_NAME: seed-app
  REPOSITORY: llm-app-images
  CHART_PATH: llm-chart/values.yaml

permissions:
  contents: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/745580653715/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          token_format: access_token
          access_token_lifetime: 300s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./seed-app
          push: true
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
      - name: Update values.yaml with new image tag
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
          yq -i '.seedApp.image.tag = "${{ github.sha }}"' ${{ env.CHART_PATH }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ${{ env.CHART_PATH }}
          git diff --staged --quiet || git commit -m "ci: update image tag for seed-app to ${{ github.sha }}"
          git push