name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: llm-pipeline-birkbeck
  GAR_LOCATION: europe-west2
  IMAGE_NAME: seed-app
  REPOSITORY: llm-app-images

jobs:
  build-and-push:
    name: Build and Push to Google Artifact Registry
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/745580653715/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

      - name: Set up Gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker credentials
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./seed-app
          push: true
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}